/* LOADING */
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';

/* REQUEST */
export const UPDATE_REQUEST_FULL = 'UPDATE_REQUEST_FULL';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_REQUEST_LOCATION = 'UPDATE_REQUEST_LOCATION';
export const UPDATE_REQUEST_EXTRA_VALUE = 'UPDATE_REQUEST_EXTRA_VALUE';

/* ANSWER */
export const UPDATE_ANSWER_FULL = 'UPDATE_ANSWER_FULL';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const UPDATE_ANSWER_TONE = 'UPDATE_ANSWER_TONE';